#define VCOUNT_POINT 1 //point
#define VCOUNT_LINE 2 //line
#define VCOUNT_QUAD 4 //quad
#define VCOUNT_ELLIPSE 5//circle

//type of emmission for all emitter types or points
#define EMT_TYPE_GRADUAL 0

//type of emissions for lines
#define EMT_TYPE_RAIN 1 //particles are fired with random angle wrt normal of line
#define EMT_TYPE_LAZER 2 //fires particles in a line in normal of line

//type of emissions for quads
#define EMT_TYPE_DUST 4
#define EMT_TYPE_DISINTEGRATE 5 // the tetricity block disintegrate

//presets for emitters
#define ALPHA_OVER_LIFETIME 0 //decreasing alpha over lifetime
#define SIZE_OVER_LIFETIME 1 //decreasing size over lifetime
#define ALPHA_SIZE_DECR_OVER_LIFETIME 2  //decreasing alpha and size over lifetime
#define ALPHA_SIZE_INCR_OVER_LIFETIME 3  //increasing alpha and size over lifetime

//for variables inside the variable ssbo
#define VARIABLE_RAND_IDX 0 // variable for Random. increments everytime rand is called
#define VARIABLE_PARTICLE_COUNT 1 // keep track of particle count thro all gpu threads

struct Emitter {
    //for now, only supporting oct mesh emission
    vec4 vertices[8];  // 4 vec4s, each vec4 is 16 bytes, total 64 bytes
    //color
    vec4 col;          // 16 bytes
    vec3 vel;          // vec3
    vec3 gravity;
    vec2 size;         // vec2

    //since particles are billboard, means that angle velocity is 2d
    float angvel;
    //lifetime of each particle
    float lifetime;         // 4 bytes
    float speed;            // 4 bytes

    // total duration the Emitter has existed for
    float time;             // 4 bytes
    float frequency;        // 4 bytes

    int type;               // 4 bytes
    int vCount;             // 4 bytes
    int preset;             // 4 bytes
    int particlesPerFrame;  // 4 bytes

    bool alive;             // 1 byte (in practice, often treated as 4 bytes for alignment)
};

struct Particle {
    vec4 col;          // vec4
    vec3 pos;          // vec3
    vec3 vel;          // vec3
    vec3 gravity;
    vec2 size;         // vec3
    float angvel;
    float age;
    float lifetime;
    int emtIdx;
    bool alive;
};


//they are the same size owo
layout(std430, binding=11) buffer Vars //the index for variables, increments every time random() is called
{ uint Variables[]; };
layout(std430, binding=12) buffer Rands //list of random floats generated by the cpu
{ float RandomFloats[]; };  
layout( std430, binding=13 ) buffer Emts
{ Emitter Emitters[]; };
layout( std430, binding=14 ) buffer Pctls
{ Particle Particles[]; };
layout( std430, binding=15 ) buffer PctlsStrt
{ Particle ParticlesStart[]; };