#pragma once
#include <Asset/Assetables/Mesh/ModelAsset.h>
#include <Asset/Assetables/Audio/AudioAsset.h>
#include <Asset/Assetables/Prefab/PrefabAsset.h>
#include <Asset/Assetables/Texture/TextureAsset.h>
#include <Asset/Assetables/Font/FontAsset.h>
#include <Asset/Assetables/Shader/ShaderAsset.h>
#include <Asset/Assetables/Material/MaterialAsset.h>
#include <Asset/Assetables/Animation/AnimationAsset.h>
#include <Asset/Assetables/Video/VideoAsset.h>
